### ISSUE TITLE
Appimage doesn't start on Archlinux

### ISSUE THREAD

**Issue by jarda-wien** [GitFiend/Support#16]
The appimage doesn't seem to work on my Archlinux install:
```
[jarda-wien@tablet:~]$ uname -a
Linux tablet 5.2.14-arch2-1-ARCH #1 SMP PREEMPT Thu Sep 12 10:42:38 UTC 2019 x86_64 GNU/Linux
[jarda-wien@tablet:~]$ GitFiend-0.19.5.AppImage 
bash: /home/jarda-wien/bin/GitFiend-0.19.5.AppImage: cannot execute binary file: Exec format error
[jarda-wien@tablet:~]$ ls -sail ~/bin/GitFiend-0.19.5.AppImage 
202952 75568 -rwxr-xr-x 1 jarda-wien jarda-wien 77375914 Sep 19 14:01 /home/jarda-wien/bin/GitFiend-0.19.5.AppImage
[jarda-wien@tablet:~]$ strace GitFiend-0.19.5.AppImage 
execve("/home/jarda-wien/bin/GitFiend-0.19.5.AppImage", ["GitFiend-0.19.5.AppImage"], 0x7fffb5537250 /* 45 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
```

**Comment by GitFiend** [comment]
That’s a shame. So it looks like you’ve done everything right (64 bit OS, made it executable). Unless it’s an incomplete download it should be working. 

I’ll look into it when I’m back from holiday in a couple of weeks.

**Comment by Jahroots** [comment]
I have almost the same issue. 

$ uname -a                     
Linux ManjaroIppon 4.14.141-1-MANJARO #1 SMP PREEMPT Thu Aug 29 13:20:24 UTC 2019 x86_64 GNU/Linux

$ ./GitFiend-0.19.5.AppImage
[16180:1003/104500.598914:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_GitFieBzqQaA/chrome-sandbox is owned by root and has mode 4755.
[1]    16180 trace trap (core dumped)  ./GitFiend-0.19.5.AppImage

**Comment by grevius5** [comment]
I have no issue with:
Linux manjaro-pc 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux
All work as aspected.

**Comment by jarda-wien** [comment]
I tried after a while (and a laptop switch). It still doesn't work, unfortunately.
```
strace ./GitFiend-0.20.3.AppImage 
execve("./GitFiend-0.20.3.AppImage", ["./GitFiend-0.20.3.AppImage"], 0x7ffe030cdf30 /* 43 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
uname -a
Linux T495 5.4.3-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 13 Dec 2019 09:40:17 +0000 x86_64 GNU/Linux
```

**Comment by GitFiend** [comment]
Hi @jarda-wien . Thanks for letting me know. There's a new version of the tool I use to make the AppImage so I'm hoping that will help.

**Comment by DaveJarvis** [comment]
Same or similar issue.

``` bash
$ wget https://gitfiend.com/resources/GitFiend-0.42.1.AppImage
$ chmod +x GitFiend-0.42.1.AppImage
$ ./GitFiend-0.42.1.AppImage
[77915:0922/130434.735599:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_GitFieG2xuPu/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
[0922/130434.787856:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.
$ uname -a
Linux hostname 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux 10 \n \l
```
